sudo: required
services:
    - docker

before_install:
    - docker build -t deepak2985/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run deepak2985/react-test npm test

after_success:
    - docker build -t deepak2985/multi-client ./client
    - docker build -t deepak2985/multi-server ./server
    - docker build -t deepak2985/multi-nginx ./nginx
    - docker build -t deepak2985/multi-worker ./worker
    #Login to the docker CLI
    -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to dockerhub
    - docker push deepak2985/multi-client
    - docker push deepak2985/multi-server
    - docker push deepak2985/multi-nginx
    - docker push deepak2985/multi-worker

    