version: "3"
services:
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        restart: always
    postgres:
        image: "postgres:latest"
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: "redis:latest"
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - C:/Users/ab41504/Pictures/docker apps/complex/server:/app
        depends_on:
            - postgres
        environment: 
                - REDIS_HOST=redis
                - REDIS_PORT=6379
                - PGUSER=postgres
                - PGHOST=postgres
                - PGDATABASE=postgres
                - PGPASSWORD=postgres_password
                - PGPORT=5432
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - C:/Users/ab41504/Pictures/docker apps/complex/client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - C:/Users/ab41504/Pictures/docker apps/complex/worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        
            
